apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: reddit-harvester-hot
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: reddit-config2
    namespace: ""
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: reddit_harvester_hot.main
    packageref:
      name: reddit-harvester-hot
      namespace: ""
  requestsPerPod: 1
  resources: {}
