include:
- ./functions/mastodon/__init__.py
- ./functions/mastodon/mastodonApi.py
- ./functions/mastodon/requirements.txt
- ./functions/mastodon/build.sh
kind: ArchiveUploadSpec
name: functions-mastodon---init---py-m3Lx

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mastodon
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-mastodon---init---py-m3Lx
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-04-21T05:48:05Z"
