apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: mastondon-trigger
spec:
  createingress: false
  functionref:
    functionweights: null
    name: mastondon
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /mastodon
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /mastodon
